development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bankapp_development
  pool: 5
  username: root

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bankapp_test
  pool: 5
  username: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bankapp_produciton
  pool: 5
  username: root

cucumber:
  <<: *test
